spring.application.name=gestion_employes
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_employes?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Yasserder78@
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false

server.port=8080
server.address=localhost